metrics:
  remove:
    - my_app.profile.**.95percentile
    - my_app.profile.**.median
    - my_app.profile.*.avg
    - top_level_metric

  keep:
    - my_app.profile.some.important.function.95percentile
