# should be one of DEBUG, INFO, WARN, ERROR or FATAL
log_level: DEBUG

# should be a list of paths to pruning configs
pruning_configs:
  - test_fixtures/pruning_configs/1.yml
  - test_fixtures/pruning_configs/2.yml
