# this config shoul be equivalent to the other 4
# TODO wkpo more tests: a test on **, on *, on duplicated tags...
# TODO wkpo rename config to pruningConfig

metrics:
  remove:
    - my_app.**.max
    - my_app.**.min
    - my_app.profile.**.95percentile
    - my_app.profile.**.median
    - my_app.profile.*.avg
    - top_level_metric

  keep:
    - my_app.profile.some.important.function.95percentile
    - my_app.profile.some.important.function.median

tags:
  remove:
    - metrics:
      - my_app.**
      tags:
      - role
    - metrics:
      - my_app.elasticsearch.count
      tags:
      - host
    - metrics:
      - another_top_level_metric
      tags:
      - whatever
    - metrics:
      - '**'
      tags:
      - hide_this
    - metrics:
      - '*'
      - not_for_top_level_metrics

  keep:
    - metrics:
      - hey.there
      tags:
      - hide_this
