# this config shoul be equivalent to the other 4
# TODO wkpo more tests: a test on **, on *, on duplicated tags...

remove_metrics:
  - my_proj.**.max
  - my_proj.**.min
  - my_proj.profile.**.95percentile
  - my_proj.profile.**.median
  - my_proj.profile.*.avg
  - top_level_metric

remove_tags:
  - metrics:
    - my_proj.**
    tags:
    - role
  - metrics:
    - my_proj.elasticsearch.count
    tags:
    - host
  - metrics:
    - another_top_level_metric
    tags:
    - whatever
